apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
      - grafana.geena.live
    secretName: wildcard-certificate-tls
  rules:
  - host: grafana.geena.live
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 80
